### ISSUE TITLE
Create documents outlining ML based audio source separation

### ISSUE THREAD

**Issue by cczarnuch** [McMasterAI/isolate#1]

**Comment by cczarnuch** [comment]
# Description
Create a report of an existing solution for separating tracks from a single file. The report should contain:
- Dataset used for training and testing
- preprocessing of inputs
- Evaluation metric performance
- Data flow
- Model used
- Tools/libraries used
Place completed doc in subfolder docs/existing_solutions

# Acceptance Criteria
- [ ] Points above are included in report
- [ ] Peer review complete
- [ ] Solution being worked on is stated in the comments

**Comment by DanDiCesare** [comment]
Some existing solutions to look at:

- [CrossNet-UMX (X-UMX)](https://arxiv.org/pdf/2010.04228.pdf)
- [openunmix](https://www.theoj.org/joss-papers/joss.01667/10.21105.joss.01667.pdf)
- [spleeter](https://joss.theoj.org/papers/10.21105/joss.02154.pdf)
- [CatNet](https://arxiv.org/pdf/2102.09966.pdf)
- [Wave-U-Net](https://arxiv.org/pdf/1806.03185.pdf)

**Comment by NickMateus11** [comment]
Some additional solutions:

- [Asteroid](https://github.com/asteroid-team/asteroid)
- [Demucs](https://github.com/facebookresearch/demucs)
- [NUSSL](https://github.com/nussl/nussl)

**Comment by BornaSadeghi** [comment]
I'm going to be looking at this implementation: https://paperswithcode.com/paper/attention-is-all-you-need-in-speech

**Comment by DanDiCesare** [comment]
I am working on Wave-U-Net.

**Comment by AllenAnZifeng** [comment]
I will be working on Spleeter.

**Comment by NickMateus11** [comment]
I will create a doc on Demucs
