### ISSUE TITLE
Explore existing source separation libraries

### ISSUE THREAD

**Issue by DanDiCesare** [McMasterAI/isolate#12]
# Description

Several source separation libraries exist that provide a good framework to work with datasets and models. These can be used to speed up development and allow for easier hosting/access to training data.

Some of these include:
- [nussl](https://github.com/nussl/nussl)
- [asteroid](https://github.com/asteroid-team/asteroid)
- [pyfasst](https://github.com/wslihgt/pyfasst) | based on [FAAST](http://bass-db.gforge.inria.fr/fasst/)

# Acceptance Criteria
- [ ] Notebook created for each of the libraries
- [ ] Summary of the available features
  - [ ] Datasets
  - [ ] Model architectures
  - [ ] Modularity
  - [ ] Documentation sources

**Comment by dufaultc** [comment]
Covered by stories 11 & 14
