### ISSUE TITLE
Create initial folder structure

### ISSUE THREAD

**Issue by cczarnuch** [McMasterAI/isolate#2]
# Description
Initialize the repo for ability to install as a python package. Add folders/files that are not already included such as:
- preprocessing
- training
- inference
- test
- setup.py
- requirements.txt
- \_\_init\_\_.py

# Acceptance Criteria
- [x] Peer review
- [x] Example files removed

**Comment by dufaultc** [comment]
An example of a similar folder structure can be seen under https://github.com/McMasterAI/Radiology-and-AI
- preprocessing
- training
- inference
- test
should be folders under src, with an empty \_\_init\_\_.py file in each as well as one in src

requirements.txt and setup.py go in the root folder of the project. For now leave requirements.txt empty.

If you have any questions feel free to send me a message.
