### ISSUE TITLE
Create Initial Readme

### ISSUE THREAD

**Issue by cczarnuch** [McMasterAI/isolate#3]
# Description
Create the initial Readme.md file. Give a background of the project and its goals. Some sections may include:
- About the Project
- Goal
- Installation
- Usage
- License
- Acknowledgements

# Acceptance Criteria
- [ ] Peer reviewed
- [ ] Initial readme created.

**Comment by dufaultc** [comment]
Create an empty section in the readme for each of these categories.

For now you only need to fill out the about the project and goal section. Fill in these sections with a small section detailing the problem were trying to solve (music source separation) and what we hope to accomplish (create system for solving this problem which performs well compared to other tools)

If you have any questions feel free to send me a message.
